[package]
name = "day_01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fancy-regex = "0.12.0"
test-case = "3.3.1"

[dev-dependencies]
assert_cmd = "2.0.2"
