[package]
name = "day_0x"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools="0.10.5"

[dev-dependencies]
assert_cmd = "2.0.7"
rstest = "0.16.0"
