[package]
name = "day_06"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.7.0"

[dev-dependencies]
assert_cmd = "2.0.6"
test-case = "2.2.2"